site_name: ovni
docs_dir: doc
extra_css: [extra.css]
theme:
  name: readthedocs
  sticky_navigation: false
  highlightjs: true
  hljs_languages:
    - abnf
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - mdx_math:
      use_gitlab_delimiters: true
      enable_dollar_delimiter: true
      add_preview: true
  - toc:
      permalink: "#"
      separator: "_"
nav:
  - index.md
  - 'User guide':
    - user/installation.md
    - 'Concepts':
      - user/concepts/part-model.md
      - user/concepts/trace.md
    - 'Runtime':
      - user/runtime/index.md
      - user/runtime/env.md
      - user/runtime/mark.md
      - user/runtime/distributed.md
      - user/runtime/kernel.md
      - user/runtime/trace_spec.md
    - 'Emulation':
      - user/emulation/index.md
      - user/emulation/mpi.md
      - user/emulation/nanos6.md
      - user/emulation/nodes.md
      - user/emulation/nosv.md
      - user/emulation/openmp.md
      - user/emulation/ovni.md
      - user/emulation/tampi.md
      - user/emulation/events.md
      - user/emulation/versions.md
    - CHANGELOG.md
  - 'Developer guide':
    - dev/index.md
    - dev/events.md
    - dev/channels.md
    - dev/patchbay.md
    - dev/mux.md
    - dev/paraver.md
    - dev/model.md
    - dev/extend.md
